#!/bin/bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

print_warning() { echo "WARNING:$1"; }
print_info() { echo "INFO:$1"; }
print_success() { echo "SUCCESS:$1"; }
t() { echo "$1"; }

source "$SCRIPT_DIR/lib/colors.sh"
source "$SCRIPT_DIR/lib/i18n.sh"
source "$SCRIPT_DIR/tests/assert-helpers.sh"
source "$SCRIPT_DIR/lib/pnpm-overrides.sh"

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

cd "$tmpdir"

npm() {
    case "$2" in
        'elliptic@6.6.2'|'elliptic@^6.6.2') return 1 ;;
        'elliptic') echo "6.6.1" ;;
        '@tootallnate/once@2.0.1'|'@tootallnate/once@^2.0.1') echo "2.0.1" ;;
        '@babel/core@^7.29.1') echo "7.29.6" ;;
        'tar@^7.5.7') echo "7.5.7" ;;
        *) return 1 ;;
    esac
}

cat > pnpm-workspace.yaml << 'EOF'
# generated by pnpm audit --fix override
pnpm:
  overrides:
    '@babel/core@<=7.29.0': ^7.29.1
    elliptic@<=6.6.1: ^6.6.2
    tar@<7.5.7: ^7.5.7
    '@tootallnate/once@2.0.1': npm:@tootallnate/once@2.0.1
  minimumReleaseAgeExclude:
    - elliptic@6.6.2
    - '@tootallnate/once@2.0.1'
    - '@babel/traverse@<=7.26.4 || ^7.26.4'
EOF

fix_pnpm_overrides ""

content=$(cat pnpm-workspace.yaml)
assert_contains "$content" "elliptic@<=6.6.1: ^6.6.1" "phantom override replaced with latest real"
assert_not_contains "$content" "6.6.2" "phantom version removed everywhere"
assert_contains "$content" "- elliptic@6.6.1" "exclude corrected to latest real"
assert_contains "$content" "'@babel/core@<=7.29.0': ^7.29.1" "scoped quoted override unchanged"
assert_contains "$content" "npm:@tootallnate/once@2.0.1" "npm protocol value untouched"
assert_contains "$content" "tar@<7.5.7: ^7.5.7" "real range unchanged"
assert_contains "$content" "|| ^7.26.4" "multi-version exclude untouched"
assert_contains "$content" "- '@tootallnate/once@2.0.1'" "scoped exclude unchanged"

cat > pnpm-workspace.yaml << 'EOF'
pnpm:
  overrides:
    elliptic@<=6.6.1: ^6.6.2
EOF

PACKAGE_VERSION_DETAILS=$'elliptic\t6.5.7\t6.6.1'
fix_pnpm_overrides "$PACKAGE_VERSION_DETAILS"

content=$(cat pnpm-workspace.yaml)
assert_contains "$content" "elliptic@<=6.6.1: ^6.6.1" "patched version from details preferred"

rm -f pnpm-workspace.yaml
fix_pnpm_overrides ""

if [ -f pnpm-workspace.yaml ]; then
    printf 'Assertion failed for no workspace file\nExpected: no file created\n' >&2
    exit 1
fi

printf 'OK\n'
